// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: credits.sql

package db

import (
	"context"
)

const upsertCredit = `-- name: UpsertCredit :exec
INSERT INTO credits (
  id
) VALUES (
  $1
)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) UpsertCredit(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.upsertCreditStmt, upsertCredit, id)
	return err
}
