// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: genres.sql

package db

import (
	"context"
)

const upsertGenre = `-- name: UpsertGenre :one
INSERT INTO genres (
  id, name
) VALUES (
  $1, $2
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name
RETURNING id, name
`

type UpsertGenreParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpsertGenre(ctx context.Context, arg UpsertGenreParams) (Genre, error) {
	row := q.queryRow(ctx, q.upsertGenreStmt, upsertGenre, arg.ID, arg.Name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
